<?php

return [
    "Krankplätze müssen verdichtet sein.",
    "Nicht so tief, Rüdiger!",
    "Frag nicht was für Saft",
    "Wollt ihr Kinder WOAS ZUM NOASCHEN!?",
    "Sie haben fett vergessen!",
    "Der ... Künstlaaahhhhhhhhhhhhh",
    "ZACK, Pfeil im Nacken!",
    "HALT STOP!",
    "Das bleibt alles so wie's hier ist!",
    "Nein! Doch! Oooh!",
    "Der Gerät wird niemals müde.",
    "Sprich Deutsch du Hurensohn.",
    "Sie haben mich ins Gesicht gefilmt. Das dürfen Sie nicht.",
    "Warum liegt hier Stroh rum?",
    "Alarm! Alarm!",
    "Ich muss raaaaus",
    "Woran hattes jelegen?",
    "Ich weise diese Unterstellungen zurück! Unterstellungen sind ...",
    "ZeeeeRRRRooooo",
    "Ich bin der Uwe und ich bin auch dabei.",
    "Anzeige ist raus.",
    "Ja leck mich doch am Zückerli.",
];
